micronaut:
  server:
    port: 32192
    cors:
      enabled: true
    netty:
      log-level: TRACE
  application:
    name: zulia-service
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
endpoints:
  routes:
    enabled: true


