micronaut:
  server:
    port: 32192
    cors:
      enabled: true
    netty:
      log-level: TRACE
  application:
    name: zulia-service
endpoints:
  routes:
    enabled: true
mongodb:
  uri: mongodb://localhost:27017/zulia

